---
- name: Post Ubuntu Install
  hosts: all
  become: yes
  
  tasks:
  
  - name: "Update Repository cache"
    apt:
    update_cache: true
    cache_valid_time: 3600
    force_apt_get: true
    
  - name: "Update cache & Full system update"
    apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600
    force_apt_get: true
    
  - name: "creating users"
    user: 
      name: reizvih
      state: present
      name: troickiy
      state: present
  
  - name: "create groups"
    group:
      name: "{{ item }}"
      state: present
    loop:
      - reizvih
      - troickiy