---
- name: Post Ubuntu Install
  hosts: all
  become: yes
  
  tasks:
  
  - name: "Update Repository cache"
    apt:
    update_cache: true
    cache_valid_time: 3600
    force_apt_get: true
    
  - name: "Update cache & Full system update"
    apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600
    force_apt_get: true
    
  - name: "creating users"
    user: 
      name: reizvih
      state: present
      name: troickiy
      state: present
  
  - name: "create groups"
    group:
      name: "{{ item }}"
      state: present
    loop:
      - reizvih
      - troickiy
     
  - name: "add reizvih to groups"
    ansible.builtin.user:
      name: reizvih
      shell: /bin/bash
      groups: reizvih,sudo
      append: yes
      
  - name: "add troickiy to groups"
    ansible.builtin.user:
      name: troickiy
      shell: /bin/bash
      groups: troickiy,sudo
      append: yes
      
  - name: "put reizvih key to server"
    authorized_key:
       user: reizvih
       state: present
       key: "{{ lookup('file', '/Users/v.reizvih/.ssh/reizvih/rsa.pub') }}"
       
  - name: "put troickiy key to server"
    authorized_key:
       user: troickiy
       state: present
       key: "{{ lookup('file', '/Users/v.reizvih/.ssh/troickiy/rsa.pub') }}"